name: Build CSVs daily

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DEBUG_HTML: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: System deps (Tesseract OCR)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: 1) Raspar lojas (gera ofertas_full.csv + produtos_primary.csv)
        run: python scrape_stores.py

      - name: 2) Baixar TODOS os produtos do OFF (gera produtos_off.csv)
        run: python seed_off_full.py

      - name: 3) Construir catálogo final (lojas PRIORIDADE + OFF complemento) → produtos.csv
        run: python build_catalog.py

      - name: 4) Consolidar preços (estima por lojas; OFF só se nenhuma loja tiver)
        run: python merge_offers.py

      - name: Commit outputs
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*.csv || true
          git add out/debug/*.html || true
          git commit -m "update CSVs + debug html" || exit 0
          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin "HEAD:$BRANCH_NAME"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csvs
          path: |
            out/*.csv
            out/debug/*.html
