name: Build CSVs daily

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DEBUG_HTML: "1"   # deixa ligado nas primeiras execuções

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: System deps (Tesseract OCR p/ Cactus)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: 1) Raspar supermercados (gera ofertas_full.csv + produtos_primary.csv)
        run: python scrape_stores.py

      - name: 2) Baixar catálogo do OFF (gera produtos_off.csv)
        run: python seed_off_catalog.py

      - name: 3) Unir catálogo (lojas + OFF) → produtos.csv
        run: python build_products_union.py

      - name: 4) Consolidar preços (snapshot + promo + estimativa + OFF fallback)
        run: python merge_offers.py

      - name: Commit CSVs
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*.csv || true
          git add out/debug/*.html || true
          git commit -m "update CSVs (full/snapshot/promocoes/produtos)" || exit 0
          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin "HEAD:$BRANCH_NAME"

      - name: Upload CSVs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csvs
          path: |
            out/*.csv
            out/debug/*.html
