name: Build CSVs daily

permissions:
  contents: write   # permite dar push dos CSVs

on:
  schedule:
    - cron: "0 4 * * *"   # roda todos os dias 04:00 UTC (~06:00 LU no verão)
  workflow_dispatch: {}   # também podes rodar manualmente pelo botão "Run workflow"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 1) Raspar lojas (gera ofertas_full.csv + produtos_primary.csv)
        run: python scrape_stores.py

      - name: 2) Completar catálogo com OFF (gera produtos.csv)
        run: python seed_off_fallback.py

      - name: 3) Unificar preços vigentes e promoções (gera ofertas_snapshot.csv + promocoes.csv)
        run: python merge_offers.py

      - name: Commit CSVs
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*.csv || true
          git commit -m "update CSVs (full/snapshot/promocoes/produtos)" || exit 0
          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin "HEAD:$BRANCH_NAME"

      - name: Upload CSVs as artifacts (opcional, útil para baixar direto pelo Actions)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csvs
          path: out/*.csv
                - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium
